import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import Sidebar from './components/Sidebar/Sidebar';
import GlobalStyleProvider from './Providers/GlobalStyleProviders';
import ContextProvider from './Providers/ContextProvider';
import DynamicLayout from './dynamicLayout';
import NextTopLoader from 'nextjs-toploader';
const nunito = Nunito({
    weight: ['400', '500', '600', '700', '800'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'My Tasks',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <head>
                <link
                    rel='stylesheet'
                    href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css'
                    integrity='sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=='
                    crossOrigin='anonymous'
                    referrerPolicy='no-referrer'
                />
            </head>
            <body className={nunito.className}>
                <NextTopLoader
                    height={2}
                    color='#27AE60'
                    easing='cubic-bezier(0.53,0.21,0,1)'
                />
                <ContextProvider>
                    <DynamicLayout>{children}</DynamicLayout>
                </ContextProvider>
            </body>
        </html>
    );
}
